name: Mise à jour du README

on:
  schedule:
    - cron: "0 0 * * *"  # Exécute le script tous les jours à minuit
  workflow_dispatch:  # Permet de l'exécuter manuellement aussi

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Installer les dépendances
        run: pip install requests

      - name: Exécuter le script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_readme.py

      - name: Pousser les modifications
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Mise à jour automatique des langages"
          git push
        continue-on-error: true  # Évite une erreur si rien n'a changé
